version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile_dev
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "postgres://postgres:p@db_dev:5432/stable_api"
    depends_on:
      - db_dev
      - frontend
    volumes:
      - .:/app 
  frontend:
    build:
      context: ./frontend 
      dockerfile: dockerfile_dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app 
  db_dev:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p
      POSTGRES_DB: stable_api
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
