version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile_dev
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "postgres://postgres:p@db_dev:5432/stable_api"
    depends_on:
      - db_dev
      - frontend
    volumes:
      - .:/app 

  frontend:
    build:
      context: ./frontend 
      dockerfile: dockerfile_dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app 

  db_dev:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p
      POSTGRES_DB: stable_api
    networks:
      custom-network:
        ipv4_address: 192.168.10.11
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  custom-network:
    name: custom-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1

volumes:
  pg_data:
