version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "postgres://postgres:p@stable_api:5432/stable_api"
    depends_on:
      - db_dev
      - frontend
  frontend:
    build:
      context: ./frontend 
    ports:
      - "3000:3000"
  db_dev:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p
      POSTGRES_DB: stable_api
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"