version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_NAME}:${DATABASE_PORT}/${DATABASE_NAME}"
    depends_on:
      - db_dev
      - frontend
    dockerfile: dockerfile_dev
  frontend:
    build:
      context: ./frontend 
    ports:
      - "3000:3000"
    dockerfile: dockerfile_dev
  db_dev:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
    ports:
      - "5432:5432"